<?php

/**
 * Implementation of hook_form_alter.
 *
 * @param $form
 * @param $form_state
 * @param $form_id
 */
function form_styler_form_alter(&$form, &$form_state, $form_id) {
  if (!empty($form['#form_styler'])) {
    if (!isset($form['#after_build'])) {
      $form['#after_build'] = array();
    }
    $form['#after_build'][] = 'form_styler_form_after_build';
  }
}

function form_styler_init() {
}

function form_styler_theme() {
  return array(
    'form_styler_add_css_assets' => array(
      'arguments' => array(),
    ),
  );
}

/**
 * Theme function that adds
 */
function theme_form_styler_add_css_assets() {
  $path = drupal_get_path('module', 'form_styler');
  drupal_add_css($path . '/js/jqTransform/jqtransformplugin/jqtransform.css');
}

function form_styler_form_after_build($form, $form_state) {
  form_styler_add_assets();

  if (!isset($form['#attributes'])) {
    $form['#attributes'] = array();
  }
  if (!isset($form['#attributes']['class'])) {
    $form['#attributes']['class'] = '';
  }
  $form['#attributes']['class'] .= 'form-styler';

  // use a theme function to add the css assets so that themes/modules can
  // override it
  theme('form_styler_add_css_assets');

  form_styler_add_assets();

  return $form;
}

function form_styler_add_assets() {
  static $inited;

  if (!$inited) {
    $path = drupal_get_path('module', 'form_styler');
    drupal_add_js($path . '/js/jqTransform/jqtransformplugin/jquery.jqtransform.js');
    drupal_add_js($path . '/js/form_styler.js');
    $settings_js = array(
      'form_styler' => array(
        'imgPath' => '/js/jqTransform/jqtransformplugin/img/',
      ),
    );
    drupal_add_js($settings_js, 'setting');
  }
}
