<?php

/**
 * Implementation of hook_form_alter.
 *
 * @param $form
 * @param $form_state
 * @param $form_id
 */
function form_styler_form_alter(&$form, &$form_state, $form_id) {
  if (!empty($form['#form_styler'])) {
    if (!isset($form['#after_build'])) {
      $form['#after_build'] = array();
    }
    $form['#after_build'][] = 'form_styler_form_after_build';
  }
}

/**
 * Utility function that adds a flag to a form to enable styling on it.
 *
 * @param array $form
 * @param array $extra_params
 */
function form_style_enable_on_form(&$form, $extra_params = array()) {
  // enable form styler for this form
  $form['#form_styler'] = TRUE;
  // style only select elements
  $settings = array(
    'form_styler' => array_merge(array(
      'restrictElements' => array('select'),
    ), $extra_params),
  );
  drupal_add_js($settings, 'setting');
}

/**
 * Implementation of hook_theme.
 *
 * @return array
 */
function form_styler_theme() {
  return array(
    'form_styler_add_css_assets' => array(
      'arguments' => array(),
    ),
  );
}

/**
 * Theme function that adds css assets
 */
function theme_form_styler_add_css_assets() {
  $path = drupal_get_path('module', 'form_styler');
  drupal_add_css($path . '/js/jqTransform/jqtransformplugin/jqtransform.css');
}

function form_styler_form_after_build($form, $form_state) {
  form_styler_add_assets();

  if (!isset($form['#attributes'])) {
    $form['#attributes'] = array();
  }
  if (!isset($form['#attributes']['class'])) {
    $form['#attributes']['class'] = '';
  }
  $form['#attributes']['class'] .= ' form-styler';

  _form_styler_disable_resizable_textareas($form);

  // use a theme function to add the css assets so that themes/modules can
  // override it
  theme('form_styler_add_css_assets');

  form_styler_add_assets();

  return $form;
}

/**
 * Disables resizing in textareas.
 *
 * @param $form
 * @return void
 */
function _form_styler_disable_resizable_textareas(&$form) {
  foreach(element_children($form) as $key) {
    if (!is_array($form[$key])) {
      continue;
    }

    _form_styler_disable_resizable_textareas($form[$key]);

    if (isset($form[$key]['#type']) &&
        $form[$key]['#type'] == 'textarea') {
      $form[$key]['#resizable'] = FALSE;
    }
  }
}

function form_styler_add_assets() {
  static $inited;

  if (!$inited) {
    $inited = TRUE;
    $path = drupal_get_path('module', 'form_styler');
    // complement form_styler by adding jquery.actual plugin
    // this is so that form_styler can properly style hidden elements
    drupal_add_js($path . '/js/jquery.actual.js');
    drupal_add_js($path . '/js/jqTransform/jqtransformplugin/jquery.jqtransform.js');
    drupal_add_js($path . '/js/form_styler.js');
    $settings_js = array(
      'form_styler' => array(
        'imgPath' => '/js/jqTransform/jqtransformplugin/img/',
      ),
    );
    drupal_add_js($settings_js, 'setting');
  }
}
